name: Build Mainline
run-name: Build with mainline Linux 6.6.0-rc4

on:
  workflow_dispatch:
  push:
    branches:
      - '*'


jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        kernel:
          - 6.5-rc2-panthor-rk3588
          # - orangepi-5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get install gcc make libncurses-dev bison flex libssl-dev fakeroot bc autoconf automake libtool build-essential debhelper zlib1g-dev uuid-dev libblkid-dev -y

      - name: Build ${{ matrix.kernel }}
        shell: bash
        run: sudo ./build.sh ${{ matrix.kernel }}

      # - name: Build u-boot
      #   shell: bash
      #   run: sudo ./build.sh -b ${{ matrix.platform }} --mainline --uboot-only

      # - name: Build image
      #   shell: bash
      #   run: sudo ./build.sh --board ${{ matrix.platform }} --mainline --server-only

      # - name: Upload built debs
      #   shell: bash
      #   run: cd ../; mkdir images; sudo mv build/*.deb images/; sudo mv images/ linux-rk3588/images/;

      - name: dump
        run: |
          echo 'github.workspace === ${{ github.workspace }}'
          echo "GITHUB_WORKSPACE === $GITHUB_WORKSPACE"
          echo 'runner.workspace === ${{ runner.workspace }}'
          echo "RUNNER_WORKSPACE === $RUNNER_WORKSPACE"

      - name: Upload server image
        uses: actions/upload-artifact@v3
        with:
          name: linux-${{ matrix.kernel }}
          path: images/*
          if-no-files-found: error

      # - name: Clean images
      #   shell: bash
      #   run: sudo rm -rf images/*.deb

      # - name: Clean cache
      #   shell: bash
      #   run: sync && sudo rm -rf ./images/ ./build/ && sync
